# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: 
      - master
      - build-pipeline
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

#    - name: Set up Go
#      uses: actions/setup-go@v3
#      with:
#        go-version: 1.16.15

#    - name: Build
#      run: go build -v ./...

#    - name: Test
#      run: go test -v ./...

    - name: Go Release
      uses: wangyoucao577/go-release-action@v1.34
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: linux
        goarch: amd64
        goversion: 1.19
        release_tag: v1.0.0
